version: '0.0.1'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    ports:
      - '3050:80'
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - PG_USER=postgres
        - PG_DATABASE=postgres
        - PG_PASSWORD=postgres_password
        - PG_PORT=5432
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - /worker:/app

